### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by ktym4a** [ktym4a/astro-page-insight#5]
## If have other ideas, please let me know.

- [x]  Show lighthouse Score
- [x] Addition of filter function
- [x] Change UI
- [x] Add show/hide button
- [x] Add cache(not sure, it need or not)  -> maybe v0.2.x
- [ ] ~~Analysis and display in meta tags (like displaying OGP)~~
- [x] build mode enable
- [ ] integrate with astro db
- [x] Add tests
- [x] Add build step

**Comment by ktym4a** [comment]
- [ ] adding feature for PWA

**Comment by ktym4a** [comment]
- [ ] Show Indicator like current is `mobile` or `desktop`
